language: ruby
rvm: 2.2.2
sudo: false
cache: bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - "bundle exec rake db:create db:migrate RAILS_ENV=test"
script: "bundle exec rspec"